"use client";

import { Search } from "lucide-react";
import { StudentLayout, StudentSection, StudentEmpty } from "@/components/student/student-layout";
import { useStudentModel } from "@/hooks/use-student-model";

export default function SeenQuestions() {
  const { data, loading, error } = useStudentModel<any>("attemptAnswer", "limit=50");
  return <StudentLayout title="Seen questions"><StudentSection eyebrow="Question history" title="Seen questions" description="Review previously encountered questions and your answer history."><div className="grid gap-3 md:grid-cols-[1fr_180px_180px]"><label className="relative"><Search className="absolute left-3 top-3 text-slate-400" size={17}/><input className="w-full rounded-xl border border-slate-200 bg-card py-2.5 pl-10 pr-3 text-sm" placeholder="Search questions"/></label><select className="rounded-xl border border-slate-200 bg-card px-3 text-sm"><option>All subjects</option></select><select className="rounded-xl border border-slate-200 bg-card px-3 text-sm"><option>Any result</option><option>Correct</option><option>Incorrect</option></select></div>{loading ? <div className="h-64 animate-pulse rounded-2xl border border-slate-200 bg-slate-200/100"/> : error ? <div className="rounded-2xl border border-red-200 bg-red-50 p-6 text-sm text-red-700">We could not load your question history. Refresh to retry.</div> : data.length === 0 ? <StudentEmpty title="No question history" message="Start practicing to build your seen-question history." href="/student/questions/random" action="Start practice"/> : <div className="overflow-x-auto rounded-2xl border border-slate-200 bg-white"><table className="w-full min-w-[720px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-400"><tr><th className="p-4">Question</th><th>Subject</th><th>Topic</th><th>Last seen</th><th>Result</th><th>Action</th></tr></thead><tbody>{data.map((answer) => <tr key={answer.id} className="border-t border-slate-100"><td className="max-w-xs p-4 font-medium text-slate-700">{answer.question?.prompt}</td><td>{answer.question?.topic?.subject?.name ?? "-"}</td><td>{answer.question?.topic?.name ?? "-"}</td><td>{new Date(answer.createdAt).toLocaleDateString()}</td><td>{answer.isCorrect == null ? "Unanswered" : answer.isCorrect ? "Correct" : "Incorrect"}</td><td><button className="text-xs font-semibold text-sky-600">Review</button></td></tr>)}</tbody></table></div>}</StudentSection></StudentLayout>;
}
