"use client";

import Link from "next/link";
import { usePathname } from "next/navigation";
import { useAppContext } from "@/hooks/useAppContext";
import { Bell, BookOpen, BrainCircuit, FileText, GraduationCap, Home, LayoutList, Library, MessageSquare, Menu, Settings, Sparkles, Trophy, Users, X } from "lucide-react";
import { useState } from "react";

const links = [
  ["Dashboard", "/student/dashboard", Home], ["Analytics", "/student/analytics", LayoutList], ["Questions", "/student/questions", BrainCircuit], ["Past Questions", "/student/past-questions", BookOpen], ["Quizzes", "/student/quizzes", LayoutList], ["Tests", "/student/tests", FileText], ["Assignments", "/student/assignments", FileText], ["Results", "/student/results", Trophy], ["Subjects", "/student/subjects", GraduationCap], ["Media", "/student/media", Library], ["Videos", "/student/videos", Library], ["Documents", "/student/documents", FileText], ["Textbooks", "/student/textbooks", BookOpen], ["Coding", "/student/coding", Sparkles], ["Study Groups", "/student/study-groups", Users], ["Rankings", "/student/rankings", Trophy], ["Messages", "/student/messages", MessageSquare], ["Complaints & Feedback", "/student/complaints", MessageSquare], ["Profile", "/student/profile", Settings],
] as const;

export function StudentLayout({ children, title }: { children: React.ReactNode; title: string }) {
  const pathname = usePathname();
  const { user } = useAppContext();
  const [open, setOpen] = useState(false);
  const firstName = user?.name?.split(" ")[0] || "Student";
  const navigation = <nav className="grid gap-1">{links.map(([label, href, Icon]) => { const active = pathname === href || (href !== "/student/dashboard" && pathname.startsWith(`${href}/`)); return <Link onClick={() => setOpen(false)} key={href} href={href} className={`flex items-center gap-3 rounded-xl px-3 py-2.5 text-[13px] ${active ? "bg-white text-[#102a43]" : "text-slate-300 hover:bg-white/10 hover:text-white"}`}><Icon size={16} />{label}</Link>; })}</nav>;
  return <main className="min-h-[calc(100vh-58px)] bg-[#f6f7fb] text-slate-950"><div className="mx-auto flex max-w-[1600px] gap-6 lg:px-6 lg:py-6"><aside className="hidden w-64 shrink-0 rounded-2xl bg-[#102a43] p-4 text-slate-200 shadow-xl lg:block"><div className="flex items-center gap-3 border-b border-white/10 px-3 pb-6"><div className="grid h-10 w-10 place-items-center rounded-xl bg-[#f7c948] text-[#102a43]"><GraduationCap size={22} /></div><div><p className="font-semibold text-white">Kith & Kin</p><p className="text-[11px] text-slate-400">Student portal</p></div></div><p className="mb-2 mt-6 px-3 text-[10px] uppercase tracking-[0.22em] text-slate-500">Learning</p>{navigation}</aside><div className="min-w-0 flex-1"><header className="flex items-center justify-between border-b border-slate-200 bg-white px-4 py-4 sm:rounded-2xl sm:px-6"><div className="flex items-center gap-3"><button aria-label="Open navigation" onClick={() => setOpen(true)} className="rounded-lg border border-slate-200 p-2 lg:hidden"><Menu size={18} /></button><div><p className="text-xs text-slate-400">Kith & Kin / Student</p><h1 className="mt-1 text-xl font-bold text-[#102a43] sm:text-2xl">{title}</h1></div></div><div className="flex items-center gap-3"><button aria-label="Notifications" className="relative rounded-xl border border-slate-200 p-2.5 text-slate-500"><Bell size={17} /><span className="absolute right-2 top-2 h-1.5 w-1.5 rounded-full bg-orange-500" /></button><div className="hidden text-right sm:block"><p className="text-sm font-semibold text-slate-700">{user?.name || firstName}</p><p className="text-[11px] text-slate-400">Student account</p></div><div className="grid h-10 w-10 place-items-center rounded-xl bg-blue-100 font-bold text-blue-700">{firstName[0]}</div></div></header><div className="px-4 py-5 sm:px-6 lg:px-1 lg:py-6">{children}</div></div></div>{open && <div className="fixed inset-0 z-50 lg:hidden"><button aria-label="Close navigation" className="absolute inset-0 bg-slate-950/40" onClick={() => setOpen(false)} /><aside className="relative h-full w-[min(86vw,320px)] overflow-y-auto bg-[#102a43] p-4 text-slate-200 shadow-2xl"><button aria-label="Close menu" onClick={() => setOpen(false)} className="mb-5 ml-auto block rounded-lg p-2 text-slate-300"><X size={20} /></button>{navigation}</aside></div>}</main>;
}

export function StudentSection({ eyebrow, title, description, children }: { eyebrow: string; title: string; description?: string; children: React.ReactNode }) { return <div className="space-y-6"><div><p className="text-xs font-semibold uppercase tracking-[0.2em] text-sky-600">{eyebrow}</p><h2 className="mt-2 text-3xl font-bold text-[#102a43]">{title}</h2>{description && <p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500">{description}</p>}</div>{children}</div>; }

export function StudentEmpty({ title, message, href, action }: { title: string; message: string; href?: string; action?: string }) { return <div className="rounded-2xl border border-dashed border-slate-300 bg-white p-10 text-center"><BookOpen className="mx-auto text-slate-400" size={28} /><h3 className="mt-4 font-bold text-[#102a43]">{title}</h3><p className="mx-auto mt-2 max-w-md text-sm text-slate-500">{message}</p>{href && <Link href={href} className="mt-5 inline-flex rounded-xl bg-[#102a43] px-4 py-2.5 text-sm font-semibold text-white">{action}</Link>}</div>; }