"use client";

import { FormEvent, useState } from "react";
import { CircleHelp, MessageSquare } from "lucide-react";
import { StudentLayout, StudentSection, StudentEmpty } from "@/components/student/student-layout";
import { useStudentModel } from "@/hooks/use-student-model";

export default function StudentComplaints() {
  const { data, loading, error } = useStudentModel<any>("complaint", "limit=30");
  const [saving, setSaving] = useState(false);
  const [message, setMessage] = useState("");
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); setSaving(true); const response = await fetch("/api/dbhandler?model=complaint", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ title: form.get("title"), category: form.get("category"), message: form.get("message") }) }); setMessage(response.ok ? "Request submitted successfully." : "Request could not be submitted."); setSaving(false); if (response.ok) event.currentTarget.reset(); }
  return <StudentLayout title="Help & feedback"><StudentSection eyebrow="Support center" title="We're here to help" description="Submit a complaint, advice, feedback, or technical issue privately to your school."><div className="grid gap-6 lg:grid-cols-[0.85fr_1.15fr]"><aside className="rounded-2xl bg-primary p-6 text-primary-foreground"><CircleHelp className="text-accent"/><h3 className="mt-7 text-xl font-bold">How can we help?</h3><div className="mt-6 grid gap-2">{["Submit complaint","Give advice","Send feedback","Report technical problem"].map((item) => <div key={item} className="rounded-xl bg-primary-foreground/10 px-4 py-3 text-sm">{item}</div>)}</div></aside><section className="rounded-2xl border border-border bg-card p-6"><div className="flex items-center gap-3"><MessageSquare className="text-sky-600"/><h3 className="font-bold text-foreground">Submit feedback</h3></div><form onSubmit={submit} className="mt-6 grid gap-4"><label className="text-sm font-semibold text-slate-700">Subject<input name="title" required className="mt-2 w-full rounded-xl border border-slate-200 bg-card px-3 py-3 font-normal"/></label><label className="text-sm font-semibold text-slate-700">Category<select name="category" className="mt-2 w-full rounded-xl border border-slate-200 bg-card px-3 py-3 font-normal"><option value="COMPLAIN">Complaint</option><option value="ADVICE">Advice</option><option value="FEEDBACK">Feedback</option></select></label><label className="text-sm font-semibold text-slate-700">Description<textarea name="message" required rows={5} className="mt-2 w-full rounded-xl border border-slate-200 bg-card px-3 py-3 font-normal"/></label>{message && <p className="text-sm text-sky-700">{message}</p>}<button disabled={saving} type="submit" className="rounded-xl bg-primary px-4 py-3 text-sm font-semibold text-primary-foreground">{saving ? "Submitting..." : "Submit"}</button></form></section></div><section className="rounded-2xl border border-border bg-white p-6"><h3 className="font-bold text-foreground">My previous requests</h3>{loading ? <div className="mt-4 h-24 animate-pulse rounded-xl bg-slate-100"/> : error ? <p className="mt-4 text-sm text-red-600">Requests could not be loaded.</p> : data.length ? <div className="mt-4 grid gap-3">{data.map((item) => <div key={item.id} className="rounded-xl border border-border p-4"><div className="flex justify-between"><p className="font-semibold text-slate-700">{item.title}</p><span className="text-xs text-slate-500">{item.status}</span></div><p className="mt-1 text-xs text-muted-foreground">{new Date(item.createdAt).toLocaleDateString()} · {item.category}</p></div>)}</div> : <StudentEmpty title="No previous requests" message="Submitted support requests will show their date, status, and response here."/>}</section></StudentSection></StudentLayout>;
}
