"use client";

import { FormEvent, useState } from "react";
import { MessageSquare, Search, Send } from "lucide-react";
import { StudentLayout, StudentSection, StudentEmpty } from "@/components/student/student-layout";
import { useStudentModel } from "@/hooks/use-student-model";

export default function StudentMessages() {
  const { data, loading, error } = useStudentModel<any>("chatThread", "limit=30");
  const [selected, setSelected] = useState<any>(null);
  const [content, setContent] = useState("");
  const [sending, setSending] = useState(false);
  async function send(event: FormEvent) { event.preventDefault(); if (!selected || !content.trim()) return; setSending(true); await fetch("/api/dbhandler?model=chatMessage", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ threadId: selected.id, content }) }); setContent(""); setSending(false); window.location.reload(); }
  return <StudentLayout title="Messages"><StudentSection eyebrow="Conversations" title="Messages" description="Keep up with teachers, school offices, and permitted study groups."><div className="grid min-h-[520px] gap-0 overflow-hidden rounded-2xl border border-slate-200 bg-card lg:grid-cols-[280px_1fr]"><aside className="border-b border-slate-200 p-5 lg:border-b-0 lg:border-r"><label className="relative block"><Search className="absolute left-3 top-3 text-slate-400" size={16}/><input className="w-full rounded-lg border border-slate-200 py-2 pl-9 pr-3 text-sm" placeholder="Search conversations"/></label>{loading ? <div className="mt-5 h-28 animate-pulse rounded-xl bg-muted"/> : error ? <p className="mt-5 text-sm text-red-600">Conversations could not be loaded.</p> : data.length ? <div className="mt-4 grid gap-2">{data.map((thread) => <button key={thread.id} onClick={() => setSelected(thread)} className="rounded-xl border border-slate-100 p-3 text-left text-sm font-semibold text-foreground hover:bg-muted">{thread.name ?? "School conversation"}</button>)}</div> : <StudentEmpty title="No conversations" message="Your permitted conversations will appear here."/>}</aside><section className="flex flex-col p-6"><div className="flex items-center gap-3 border-b border-slate-100 pb-4"><MessageSquare className="text-sky-600"/><div><h3 className="font-bold text-[#102a43]">{selected?.name ?? "Select a conversation"}</h3><p className="text-xs text-slate-400">Messages are scoped to your account.</p></div></div><div className="flex-1 space-y-3 py-6">{selected?.messages?.length ? selected.messages.map((message: any) => <p key={message.id} className="rounded-xl bg-muted p-3 text-sm text-foreground">{message.content}</p>) : <p className="text-sm text-slate-400">Choose a conversation to view messages.</p>}</div><form onSubmit={send} className="flex gap-2"><input value={content} onChange={(event) => setContent(event.target.value)} disabled={!selected || sending} className="flex-1 rounded-xl border border-slate-200 px-3 py-3 text-sm" placeholder="Write a message"/><button disabled={!selected || sending} aria-label="Send message" className="rounded-xl bg-[#102a43] px-4 text-white"><Send size={17}/></button></form></section></div></StudentSection></StudentLayout>;
}
